server:
  port: 8082
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/springdemo
    username: root
    password: nam9mgchanh
    driver-class-name: com.mysql.cj.jdbc.Driver
open:
  api:
    title: "API document"
    description: "description"
    version: "v1.0.0"
    serverUrl: "http://localhost:${server.port}"
    serverName: "server test"