server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
open:
  api:
    title: ${API_TITLE:DUMMY-API-TITLE}
    description: "description"
    version: "v1.0.0"
    serverUrl: "http://localhost:${server.port}"
    serverName: "server test"