server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/springdemo
    username: root
    password: nam9mgchanh
    driver-class-name: com.mysql.cj.jdbc.Driver
open:
  api:
    title: ${API_TITLE:DUMMY-API-TITLE}
    description: "description"
    version: "v1.0.0"
    serverUrl: "http://localhost:${server.port}"
    serverName: "server test"