spring:
  application:
    name: "qnam-studyspring"
  profiles:
    active: ${MY_ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:mysql://localhost:3306/springdemo
    username: root
    password: nam9mgchanh
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jwt:
  signerKey: "tiq8ysiqcvKdfCRt+cPn/OYrTfrXXPA4x7Fp9nwm0UI2e8HCffQvHTRlloe9KkBKJibIDM5gv+AcdUZj3Jp8YCUN7gwwXUZk1jMUBHzIBY0="
  valid-duration: 3600 #second
  refreshable-duration: 36000 #second
  #Tuy vao ung dung ma thoi gian ton tai cua token, refresh token it hay nhieu
mail:
  from: "vuquangnam2005@gmail.com"