spring:
  application:
    name: "qnam-studyspring"
  profiles:
    active: ${MY_ACTIVE_PROFILE:dev}

jwt:
  signerKey: "tiq8ysiqcvKdfCRt+cPn/OYrTfrXXPA4x7Fp9nwm0UI2e8HCffQvHTRlloe9KkBKJibIDM5gv+AcdUZj3Jp8YCUN7gwwXUZk1jMUBHzIBY0="

